# -*- coding: utf-8 -*-
"""MultimodalSentimentAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHou2H4SKtHrxF2FnIIpjMQ0YR7FQM7-

# Multimodal Sentiment Analysis
"""

from google.colab import drive
drive.mount('/content/drive')

"""Navigate to the MELD Dataset"""

import os

meld_path = '/content/drive/MyDrive/MELD.Raw'
os.listdir(meld_path)

"""##  Pipeline Plan (Overview)

We’ll process each modality:

| Modality  | Input         | Feature Extraction          | Output  |
| --------- | ------------- | --------------------------- | ------- |
| **Text**  | Utterance     | BERT / GloVe embeddings     | Vectors |
| **Audio** | `.wav` files  | MFCCs or OpenSMILE features | Vectors |
| **Video** | `.mp4` frames | CNN (e.g., ResNet) features | Vectors |

Then we'll **fuse** all three features and feed them into a classification model (e.g., MLP, LSTM, etc.).

Extract Audio, Video, and Text Paths
"""

import pandas as pd

train_df = pd.read_csv(os.path.join(meld_path, 'train_sent_emo.csv'))
train_df.head()

dev_df = pd.read_csv(os.path.join(meld_path, 'dev_sent_emo.csv'))
dev_df.head()

test_df = pd.read_csv(os.path.join(meld_path, 'test_sent_emo.csv'))
test_df.head()

# Example: Get full audio path for a given utterance
def get_audio_path(split, Dialogue_ID, Utterance_ID):
    return os.path.join(meld_path, split, 'wav', f'dia{Dialogue_ID}_utt{Utterance_ID}.wav')

"""### Text Pipeline

preview the train set
"""

train_df[['Utterance', 'Emotion', 'Sentiment']].head()

"""preview the dev set"""

dev_df[['Utterance', 'Emotion', 'Sentiment']].head()

"""preview the test set"""

test_df[['Utterance', 'Emotion', 'Sentiment']].head()

"""Install and load BERT tokenizer and model

We’ll use bert-base-uncased from Hugging Face.
"""

!pip install transformers --quiet

from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = BertModel.from_pretrained('bert-base-uncased')

"""Define function to get BERT embeddings"""

def get_bert_embedding(text):
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128)
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze().numpy()  # Mean pooling

"""Apply to a sample"""

sample_text_train = train_df['Utterance'][0]
embedding = get_bert_embedding(sample_text_train)
print("Shape of embedding:", embedding.shape)

sample_text_dev = dev_df['Utterance'][0]
embedding = get_bert_embedding(sample_text_dev)
print("Shape of embedding:", embedding.shape)

sample_text_test = test_df['Utterance'][0]
embedding = get_bert_embedding(sample_text_test)
print("Shape of embedding:", embedding.shape)

"""Extract Text Embeddings for Entire Dataset"""

from tqdm import tqdm
import numpy as np

def embed_text_column(df, text_col='Utterance'):
    embeddings = []
    for text in tqdm(df[text_col], desc="Embedding texts"):
        embedding = get_bert_embedding(text)
        embeddings.append(embedding)
    return np.array(embeddings)

"""train"""

train_embeddings = embed_text_column(train_df)
train_embeddings.shape  # Should be (num_samples, 768)

np.save('/content/drive/MyDrive/MELD.Raw/train_text_embeddings.npy', train_embeddings)

"""dev"""

dev_embeddings = embed_text_column(dev_df)
dev_embeddings.shape  # Should be (num_samples, 768)

np.save('/content/drive/MyDrive/MELD.Raw/dev_text_embeddings.npy', dev_embeddings)

"""test"""

test_embeddings = embed_text_column(test_df)
test_embeddings.shape  # Should be (num_samples, 768)

np.save('/content/drive/MyDrive/MELD.Raw/test_text_embeddings.npy', test_embeddings)





"""### Audio pipeline

### Extracting Audio Features from MELD .wav Files

We'll extract audio features (like MFCCs or deep embeddings) from each audio clip. These features will be used alongside the text and (later) video features.

Install Required Libraries
"""

!pip install librosa soundfile --quiet

!pip install moviepy --quiet

"""Import Dependencies"""

import librosa
import numpy as np
import os
from tqdm import tqdm

"""Extract Audio from .mp4 and Save as .wav

train
"""

import os
from moviepy.editor import VideoFileClip

def extract_audio_from_video(video_path, output_audio_path):
    try:
        video_clip = VideoFileClip(video_path)
        audio = video_clip.audio
        audio.write_audiofile(output_audio_path, codec='pcm_s16le')
        audio.close()
        video_clip.close()
    except Exception as e:
        print(f"Failed to extract from {video_path}: {e}")

video_dir = '/content/drive/MyDrive/MELD.Raw/train/train_splits'
output_audio_dir = '/content/drive/MyDrive/MELD.Raw/train_audio'
os.makedirs(output_audio_dir, exist_ok=True)

for file_name in tqdm(os.listdir(video_dir)):
    if file_name.endswith('.mp4'):
        video_path = os.path.join(video_dir, file_name)
        output_path = os.path.join(output_audio_dir, file_name.replace('.mp4', '.wav'))
        extract_audio_from_video(video_path, output_path)

"""dev"""

import os
from moviepy.editor import VideoFileClip

def extract_audio_from_video(video_path, output_audio_path):
    try:
        video_clip = VideoFileClip(video_path)
        audio = video_clip.audio
        audio.write_audiofile(output_audio_path, codec='pcm_s16le')
        audio.close()
        video_clip.close()
    except Exception as e:
        print(f"Failed to extract from {video_path}: {e}")

video_dir = '/content/drive/MyDrive/MELD.Raw/dev/dev_splits_complete'
output_audio_dir = '/content/drive/MyDrive/MELD.Raw/dev_audio'
os.makedirs(output_audio_dir, exist_ok=True)

for file_name in tqdm(os.listdir(video_dir)):
    if file_name.endswith('.mp4'):
        video_path = os.path.join(video_dir, file_name)
        output_path = os.path.join(output_audio_dir, file_name.replace('.mp4', '.wav'))
        extract_audio_from_video(video_path, output_path)

"""test"""

import os
from moviepy.editor import VideoFileClip
from tqdm import tqdm

def extract_audio_from_video(video_path, output_audio_path):
    try:
        video_clip = VideoFileClip(video_path)
        audio = video_clip.audio
        audio.write_audiofile(output_audio_path, codec='pcm_s16le')
        audio.close()
        video_clip.close()
    except Exception as e:
        print(f"Failed to extract from {video_path}: {e}")

video_dir = '//content/drive/MyDrive/MELD.Raw/test/output_repeated_splits_test'
output_audio_dir = '/content/drive/MyDrive/MELD.Raw/test_audio'
os.makedirs(output_audio_dir, exist_ok=True)

for file_name in tqdm(os.listdir(video_dir)):
    # Skip hidden system files that start with ._ (AppleDouble files)
    if file_name.startswith('._'):
        continue

    if file_name.endswith('.mp4'):
        video_path = os.path.join(video_dir, file_name)
        output_path = os.path.join(output_audio_dir, file_name.replace('.mp4', '.wav'))
        extract_audio_from_video(video_path, output_path)

"""Define Audio Feature Extraction Function

We'll extract Mel-frequency cepstral coefficients (MFCCs), a popular feature for audio-based emotion analysis.

Apply to All Audio Samples

Execute on Train Data
"""

# Optimized Audio Processing - Handle Missing Files Efficiently
import librosa
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
from collections import defaultdict

def create_file_index(audio_dir):
    """
    Create an index of all available audio files for fast lookup
    This avoids repeated file system calls
    """
    print("📁 Creating file index for fast lookup...")

    all_files = [f for f in os.listdir(audio_dir) if f.endswith('.wav')]
    file_index = {}

    for file_name in all_files:
        # Extract dialogue_id and utterance_id from filename
        try:
            if 'dia' in file_name and 'utt' in file_name:
                # Handle both "dia0_utt1.wav" and "dia0_utt1 (1).wav" formats
                base_name = file_name.replace('.wav', '')
                if ' (' in base_name:
                    base_name = base_name.split(' (')[0]

                parts = base_name.split('_')
                if len(parts) >= 2:
                    dia_id = int(parts[0].replace('dia', ''))
                    utt_id = int(parts[1].replace('utt', ''))

                    key = (dia_id, utt_id)
                    if key not in file_index:
                        file_index[key] = []
                    file_index[key].append(file_name)
        except:
            continue

    # Sort files for each key (prefer original over duplicates)
    for key in file_index:
        file_index[key].sort(key=lambda x: (x.count('('), x))

    print(f"✅ Indexed {len(file_index):,} unique audio files")
    return file_index

def extract_audio_features_batch(file_paths, audio_dir, n_mfcc=13):
    """
    Extract features from a batch of files efficiently
    """
    features = []

    for file_path in file_paths:
        if file_path is None:
            features.append(np.zeros(n_mfcc))
            continue

        try:
            full_path = os.path.join(audio_dir, file_path)
            y, sr = librosa.load(full_path, sr=22050)  # Fixed sample rate for consistency

            if len(y) == 0:
                features.append(np.zeros(n_mfcc))
                continue

            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
            mfcc_mean = np.mean(mfcc.T, axis=0)
            features.append(mfcc_mean)

        except Exception as e:
            features.append(np.zeros(n_mfcc))

    return np.array(features)

def process_audio_optimized(df, audio_dir, n_mfcc=13, batch_size=100):
    """
    Optimized processing with batching and pre-indexing
    """
    # Create file index first
    file_index = create_file_index(audio_dir)

    # Pre-check which files exist
    print("🔍 Pre-checking file availability...")
    file_paths = []
    missing_count = 0

    for _, row in df.iterrows():
        key = (row['Dialogue_ID'], row['Utterance_ID'])
        if key in file_index:
            file_paths.append(file_index[key][0])  # Use first (best) available file
        else:
            file_paths.append(None)
            missing_count += 1

    print(f"📊 File availability:")
    print(f"   Available: {len(df) - missing_count:,} ({(len(df) - missing_count)/len(df)*100:.1f}%)")
    print(f"   Missing: {missing_count:,} ({missing_count/len(df)*100:.1f}%)")

    # Process in batches for better memory management
    print(f"🚀 Processing {len(df):,} files in batches of {batch_size}...")

    all_features = []
    successful = 0

    for i in tqdm(range(0, len(file_paths), batch_size), desc="Processing batches"):
        batch_paths = file_paths[i:i+batch_size]
        batch_features = extract_audio_features_batch(batch_paths, audio_dir, n_mfcc)
        all_features.append(batch_features)

        # Count successful extractions in this batch
        successful += np.sum(~np.all(batch_features == 0, axis=1))

    # Combine all features
    final_features = np.vstack(all_features)

    print(f"\n✅ Processing Results:")
    print(f"   Total samples: {len(df):,}")
    print(f"   Features extracted: {successful:,}")
    print(f"   Missing files (zero-padded): {len(df) - successful:,}")
    print(f"   Success rate: {successful/len(df)*100:.1f}%")

    return final_features, missing_count

def analyze_missing_patterns(df, audio_dir):
    """
    Analyze patterns in missing files
    """
    print("🔍 Analyzing missing file patterns...")

    file_index = create_file_index(audio_dir)
    missing_dialogues = defaultdict(list)

    for _, row in df.iterrows():
        key = (row['Dialogue_ID'], row['Utterance_ID'])
        if key not in file_index:
            missing_dialogues[row['Dialogue_ID']].append(row['Utterance_ID'])

    print(f"📊 Missing file analysis:")
    print(f"   Dialogues with missing files: {len(missing_dialogues)}")

    # Show most problematic dialogues
    if missing_dialogues:
        sorted_missing = sorted(missing_dialogues.items(),
                              key=lambda x: len(x[1]), reverse=True)

        print(f"   Top 10 dialogues with most missing files:")
        for dia_id, utt_ids in sorted_missing[:10]:
            print(f"     Dialogue {dia_id}: {len(utt_ids)} missing utterances")

    return missing_dialogues

# =============================================================================
# OPTIMIZED PROCESSING
# =============================================================================

print("🎵 MELD Audio Feature Extraction (Optimized)")
print("=" * 60)

# Configuration
audio_dir = '/content/drive/MyDrive/MELD.Raw/train_audio'
n_mfcc = 13
batch_size = 100  # Process in batches for better performance

print(f"📁 Audio directory: {audio_dir}")
print(f"📊 Dataset size: {len(train_df):,} samples")
print(f"🎯 MFCC coefficients: {n_mfcc}")
print(f"⚡ Batch size: {batch_size}")

# Analyze missing files first
missing_dialogues = analyze_missing_patterns(train_df, audio_dir)

# Process with optimized method
print(f"\n🚀 Starting optimized processing...")
train_audio_features, missing_count = process_audio_optimized(
    train_df, audio_dir, n_mfcc, batch_size
)

print(f"\n📈 Final Results:")
print(f"   Features shape: {train_audio_features.shape}")
print(f"   Expected shape: ({len(train_df)}, {n_mfcc})")
print(f"   Missing files handled: {missing_count:,}")

# Save the features
output_path = '/content/drive/MyDrive/MELD.Raw/train_audio_features.npy'
np.save(output_path, train_audio_features)
print(f"💾 Features saved to: {output_path}")

# Create a metadata file
metadata = {
    'total_samples': len(train_df),
    'successful_extractions': len(train_df) - missing_count,
    'missing_files': missing_count,
    'success_rate': (len(train_df) - missing_count) / len(train_df) * 100,
    'n_mfcc': n_mfcc,
    'feature_shape': train_audio_features.shape
}

import json
metadata_path = '/content/drive/MyDrive/MELD.Raw/train_audio_features_metadata.json'
with open(metadata_path, 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"📋 Metadata saved to: {metadata_path}")

# Feature statistics
non_zero_samples = np.count_nonzero(np.sum(train_audio_features, axis=1))
print(f"\n🔍 Feature Statistics:")
print(f"   Non-zero feature samples: {non_zero_samples:,}")
print(f"   Zero-padded samples: {len(train_df) - non_zero_samples:,}")
print(f"   Mean feature value: {np.mean(train_audio_features[train_audio_features != 0]):.4f}")
print(f"   Std feature value: {np.std(train_audio_features[train_audio_features != 0]):.4f}")

print("\n✅ Optimized audio feature extraction complete!")
print("🎯 Ready for emotion classification model training")

"""Execute on dev Data"""

# Optimized Audio Processing - Handle Missing Files Efficiently
import librosa
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
from collections import defaultdict

def create_file_index(audio_dir):
    """
    Create an index of all available audio files for fast lookup
    This avoids repeated file system calls
    """
    print("📁 Creating file index for fast lookup...")

    all_files = [f for f in os.listdir(audio_dir) if f.endswith('.wav')]
    file_index = {}

    for file_name in all_files:
        # Extract dialogue_id and utterance_id from filename
        try:
            if 'dia' in file_name and 'utt' in file_name:
                # Handle both "dia0_utt1.wav" and "dia0_utt1 (1).wav" formats
                base_name = file_name.replace('.wav', '')
                if ' (' in base_name:
                    base_name = base_name.split(' (')[0]

                parts = base_name.split('_')
                if len(parts) >= 2:
                    dia_id = int(parts[0].replace('dia', ''))
                    utt_id = int(parts[1].replace('utt', ''))

                    key = (dia_id, utt_id)
                    if key not in file_index:
                        file_index[key] = []
                    file_index[key].append(file_name)
        except:
            continue

    # Sort files for each key (prefer original over duplicates)
    for key in file_index:
        file_index[key].sort(key=lambda x: (x.count('('), x))

    print(f"✅ Indexed {len(file_index):,} unique audio files")
    return file_index

def extract_audio_features_batch(file_paths, audio_dir, n_mfcc=13):
    """
    Extract features from a batch of files efficiently
    """
    features = []

    for file_path in file_paths:
        if file_path is None:
            features.append(np.zeros(n_mfcc))
            continue

        try:
            full_path = os.path.join(audio_dir, file_path)
            y, sr = librosa.load(full_path, sr=22050)  # Fixed sample rate for consistency

            if len(y) == 0:
                features.append(np.zeros(n_mfcc))
                continue

            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
            mfcc_mean = np.mean(mfcc.T, axis=0)
            features.append(mfcc_mean)

        except Exception as e:
            features.append(np.zeros(n_mfcc))

    return np.array(features)

def process_audio_optimized(df, audio_dir, n_mfcc=13, batch_size=100):
    """
    Optimized processing with batching and pre-indexing
    """
    # Create file index first
    file_index = create_file_index(audio_dir)

    # Pre-check which files exist
    print("🔍 Pre-checking file availability...")
    file_paths = []
    missing_count = 0

    for _, row in df.iterrows():
        key = (row['Dialogue_ID'], row['Utterance_ID'])
        if key in file_index:
            file_paths.append(file_index[key][0])  # Use first (best) available file
        else:
            file_paths.append(None)
            missing_count += 1

    print(f"📊 File availability:")
    print(f"   Available: {len(df) - missing_count:,} ({(len(df) - missing_count)/len(df)*100:.1f}%)")
    print(f"   Missing: {missing_count:,} ({missing_count/len(df)*100:.1f}%)")

    # Process in batches for better memory management
    print(f"🚀 Processing {len(df):,} files in batches of {batch_size}...")

    all_features = []
    successful = 0

    for i in tqdm(range(0, len(file_paths), batch_size), desc="Processing batches"):
        batch_paths = file_paths[i:i+batch_size]
        batch_features = extract_audio_features_batch(batch_paths, audio_dir, n_mfcc)
        all_features.append(batch_features)

        # Count successful extractions in this batch
        successful += np.sum(~np.all(batch_features == 0, axis=1))

    # Combine all features
    final_features = np.vstack(all_features)

    print(f"\n✅ Processing Results:")
    print(f"   Total samples: {len(df):,}")
    print(f"   Features extracted: {successful:,}")
    print(f"   Missing files (zero-padded): {len(df) - successful:,}")
    print(f"   Success rate: {successful/len(df)*100:.1f}%")

    return final_features, missing_count

def analyze_missing_patterns(df, audio_dir):
    """
    Analyze patterns in missing files
    """
    print("🔍 Analyzing missing file patterns...")

    file_index = create_file_index(audio_dir)
    missing_dialogues = defaultdict(list)

    for _, row in df.iterrows():
        key = (row['Dialogue_ID'], row['Utterance_ID'])
        if key not in file_index:
            missing_dialogues[row['Dialogue_ID']].append(row['Utterance_ID'])

    print(f"📊 Missing file analysis:")
    print(f"   Dialogues with missing files: {len(missing_dialogues)}")

    # Show most problematic dialogues
    if missing_dialogues:
        sorted_missing = sorted(missing_dialogues.items(),
                              key=lambda x: len(x[1]), reverse=True)

        print(f"   Top 10 dialogues with most missing files:")
        for dia_id, utt_ids in sorted_missing[:10]:
            print(f"     Dialogue {dia_id}: {len(utt_ids)} missing utterances")

    return missing_dialogues

# =============================================================================
# OPTIMIZED PROCESSING
# =============================================================================

print("🎵 MELD Audio Feature Extraction (Optimized)")
print("=" * 60)

# Configuration
audio_dir = '/content/drive/MyDrive/MELD.Raw/dev_audio'
n_mfcc = 13
batch_size = 100  # Process in batches for better performance

print(f"📁 Audio directory: {audio_dir}")
print(f"📊 Dataset size: {len(dev_df):,} samples")
print(f"🎯 MFCC coefficients: {n_mfcc}")
print(f"⚡ Batch size: {batch_size}")

# Analyze missing files first
missing_dialogues = analyze_missing_patterns(dev_df, audio_dir)

# Process with optimized method
print(f"\n🚀 Starting optimized processing...")
dev_audio_features, missing_count = process_audio_optimized(
    dev_df, audio_dir, n_mfcc, batch_size
)

print(f"\n📈 Final Results:")
print(f"   Features shape: {dev_audio_features.shape}")
print(f"   Expected shape: ({len(dev_df)}, {n_mfcc})")
print(f"   Missing files handled: {missing_count:,}")

# Save the features
output_path = '/content/drive/MyDrive/MELD.Raw/dev_audio_features.npy'
np.save(output_path, dev_audio_features)
print(f"💾 Features saved to: {output_path}")

# Create a metadata file
metadata = {
    'total_samples': len(dev_df),
    'successful_extractions': len(dev_df) - missing_count,
    'missing_files': missing_count,
    'success_rate': (len(dev_df) - missing_count) / len(dev_df) * 100,
    'n_mfcc': n_mfcc,
    'feature_shape': dev_audio_features.shape
}

import json
metadata_path = '/content/drive/MyDrive/MELD.Raw/dev_audio_features_metadata.json'
with open(metadata_path, 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"📋 Metadata saved to: {metadata_path}")

# Feature statistics
non_zero_samples = np.count_nonzero(np.sum(dev_audio_features, axis=1))
print(f"\n🔍 Feature Statistics:")
print(f"   Non-zero feature samples: {non_zero_samples:,}")
print(f"   Zero-padded samples: {len(dev_df) - non_zero_samples:,}")
print(f"   Mean feature value: {np.mean(dev_audio_features[dev_audio_features != 0]):.4f}")
print(f"   Std feature value: {np.std(dev_audio_features[dev_audio_features != 0]):.4f}")

print("\n✅ Optimized audio feature extraction complete!")
print("🎯 Ready for emotion classification model training")



"""test data"""

# Optimized Audio Processing - Handle Missing Files Efficiently
import librosa
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
from collections import defaultdict

def create_file_index(audio_dir):
    """
    Create an index of all available audio files for fast lookup
    This avoids repeated file system calls
    """
    print("📁 Creating file index for fast lookup...")

    all_files = [f for f in os.listdir(audio_dir) if f.endswith('.wav')]
    file_index = {}

    for file_name in all_files:
        # Extract dialogue_id and utterance_id from filename
        try:
            if 'dia' in file_name and 'utt' in file_name:
                # Handle both "dia0_utt1.wav" and "dia0_utt1 (1).wav" formats
                base_name = file_name.replace('.wav', '')
                if ' (' in base_name:
                    base_name = base_name.split(' (')[0]

                parts = base_name.split('_')
                if len(parts) >= 2:
                    dia_id = int(parts[0].replace('dia', ''))
                    utt_id = int(parts[1].replace('utt', ''))

                    key = (dia_id, utt_id)
                    if key not in file_index:
                        file_index[key] = []
                    file_index[key].append(file_name)
        except:
            continue

    # Sort files for each key (prefer original over duplicates)
    for key in file_index:
        file_index[key].sort(key=lambda x: (x.count('('), x))

    print(f"✅ Indexed {len(file_index):,} unique audio files")
    return file_index

def extract_audio_features_batch(file_paths, audio_dir, n_mfcc=13):
    """
    Extract features from a batch of files efficiently
    """
    features = []

    for file_path in file_paths:
        if file_path is None:
            features.append(np.zeros(n_mfcc))
            continue

        try:
            full_path = os.path.join(audio_dir, file_path)
            y, sr = librosa.load(full_path, sr=22050)  # Fixed sample rate for consistency

            if len(y) == 0:
                features.append(np.zeros(n_mfcc))
                continue

            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
            mfcc_mean = np.mean(mfcc.T, axis=0)
            features.append(mfcc_mean)

        except Exception as e:
            features.append(np.zeros(n_mfcc))

    return np.array(features)

def process_audio_optimized(df, audio_dir, n_mfcc=13, batch_size=100):
    """
    Optimized processing with batching and pre-indexing
    """
    # Create file index first
    file_index = create_file_index(audio_dir)

    # Pre-check which files exist
    print("🔍 Pre-checking file availability...")
    file_paths = []
    missing_count = 0

    for _, row in df.iterrows():
        key = (row['Dialogue_ID'], row['Utterance_ID'])
        if key in file_index:
            file_paths.append(file_index[key][0])  # Use first (best) available file
        else:
            file_paths.append(None)
            missing_count += 1

    print(f"📊 File availability:")
    print(f"   Available: {len(df) - missing_count:,} ({(len(df) - missing_count)/len(df)*100:.1f}%)")
    print(f"   Missing: {missing_count:,} ({missing_count/len(df)*100:.1f}%)")

    # Process in batches for better memory management
    print(f"🚀 Processing {len(df):,} files in batches of {batch_size}...")

    all_features = []
    successful = 0

    for i in tqdm(range(0, len(file_paths), batch_size), desc="Processing batches"):
        batch_paths = file_paths[i:i+batch_size]
        batch_features = extract_audio_features_batch(batch_paths, audio_dir, n_mfcc)
        all_features.append(batch_features)

        # Count successful extractions in this batch
        successful += np.sum(~np.all(batch_features == 0, axis=1))

    # Combine all features
    final_features = np.vstack(all_features)

    print(f"\n✅ Processing Results:")
    print(f"   Total samples: {len(df):,}")
    print(f"   Features extracted: {successful:,}")
    print(f"   Missing files (zero-padded): {len(df) - successful:,}")
    print(f"   Success rate: {successful/len(df)*100:.1f}%")

    return final_features, missing_count

def analyze_missing_patterns(df, audio_dir):
    """
    Analyze patterns in missing files
    """
    print("🔍 Analyzing missing file patterns...")

    file_index = create_file_index(audio_dir)
    missing_dialogues = defaultdict(list)

    for _, row in df.iterrows():
        key = (row['Dialogue_ID'], row['Utterance_ID'])
        if key not in file_index:
            missing_dialogues[row['Dialogue_ID']].append(row['Utterance_ID'])

    print(f"📊 Missing file analysis:")
    print(f"   Dialogues with missing files: {len(missing_dialogues)}")

    # Show most problematic dialogues
    if missing_dialogues:
        sorted_missing = sorted(missing_dialogues.items(),
                              key=lambda x: len(x[1]), reverse=True)

        print(f"   Top 10 dialogues with most missing files:")
        for dia_id, utt_ids in sorted_missing[:10]:
            print(f"     Dialogue {dia_id}: {len(utt_ids)} missing utterances")

    return missing_dialogues

# =============================================================================
# OPTIMIZED PROCESSING
# =============================================================================

print("🎵 MELD Audio Feature Extraction (Optimized)")
print("=" * 60)

# Configuration
audio_dir = '/content/drive/MyDrive/MELD.Raw/test_audio'
n_mfcc = 13
batch_size = 100  # Process in batches for better performance

print(f"📁 Audio directory: {audio_dir}")
print(f"📊 Dataset size: {len(test_df):,} samples")
print(f"🎯 MFCC coefficients: {n_mfcc}")
print(f"⚡ Batch size: {batch_size}")

# Analyze missing files first
missing_dialogues = analyze_missing_patterns(test_df, audio_dir)

# Process with optimized method
print(f"\n🚀 Starting optimized processing...")
test_audio_features, missing_count = process_audio_optimized(
    test_df, audio_dir, n_mfcc, batch_size
)

print(f"\n📈 Final Results:")
print(f"   Features shape: {test_audio_features.shape}")
print(f"   Expected shape: ({len(test_df)}, {n_mfcc})")
print(f"   Missing files handled: {missing_count:,}")

# Save the features
output_path = '/content/drive/MyDrive/MELD.Raw/test_audio_features.npy'
np.save(output_path, test_audio_features)
print(f"💾 Features saved to: {output_path}")

# Create a metadata file
metadata = {
    'total_samples': len(test_df),
    'successful_extractions': len(test_df) - missing_count,
    'missing_files': missing_count,
    'success_rate': (len(test_df) - missing_count) / len(test_df) * 100,
    'n_mfcc': n_mfcc,
    'feature_shape': test_audio_features.shape
}

import json
metadata_path = '/content/drive/MyDrive/MELD.Raw/test_audio_features_metadata.json'
with open(metadata_path, 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"📋 Metadata saved to: {metadata_path}")

# Feature statistics
non_zero_samples = np.count_nonzero(np.sum(test_audio_features, axis=1))
print(f"\n🔍 Feature Statistics:")
print(f"   Non-zero feature samples: {non_zero_samples:,}")
print(f"   Zero-padded samples: {len(test_df) - non_zero_samples:,}")
print(f"   Mean feature value: {np.mean(test_audio_features[test_audio_features != 0]):.4f}")
print(f"   Std feature value: {np.std(test_audio_features[test_audio_features != 0]):.4f}")

print("\n✅ Optimized audio feature extraction complete!")
print("🎯 Ready for emotion classification model training")

# Enhanced Audio Processing - Advanced Missing Data Handling
import librosa
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
from collections import defaultdict
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
import json
import warnings
warnings.filterwarnings('ignore')

class AudioFeatureExtractor:
    def __init__(self, audio_dir, n_mfcc=13, sr=22050, hop_length=512, n_fft=2048):
        self.audio_dir = audio_dir
        self.n_mfcc = n_mfcc
        self.sr = sr
        self.hop_length = hop_length
        self.n_fft = n_fft
        self.file_index = {}
        self.scaler = StandardScaler()

    def create_file_index(self):
        """Enhanced file indexing with better pattern matching"""
        print("📁 Creating enhanced file index...")

        all_files = [f for f in os.listdir(self.audio_dir)
                    if f.lower().endswith(('.wav', '.mp3', '.flac', '.m4a'))]

        patterns = [
            r'dia(\d+)_utt(\d+)',  # dia0_utt1.wav
            r'dialogue_(\d+)_utterance_(\d+)',  # dialogue_0_utterance_1.wav
            r'd(\d+)u(\d+)',  # d0u1.wav
            r'(\d+)_(\d+)'  # 0_1.wav
        ]

        import re
        for file_name in all_files:
            for pattern in patterns:
                match = re.search(pattern, file_name.lower())
                if match:
                    dia_id, utt_id = map(int, match.groups())
                    key = (dia_id, utt_id)
                    if key not in self.file_index:
                        self.file_index[key] = []
                    self.file_index[key].append(file_name)
                    break

        # Sort files for each key (prefer original over duplicates)
        for key in self.file_index:
            self.file_index[key].sort(key=lambda x: (x.count('('), len(x), x))

        print(f"✅ Indexed {len(self.file_index):,} unique audio files")
        return self.file_index

    def extract_advanced_features(self, file_path):
        """Extract comprehensive audio features"""
        try:
            full_path = os.path.join(self.audio_dir, file_path)
            y, sr = librosa.load(full_path, sr=self.sr)

            if len(y) == 0:
                return np.zeros(self.n_mfcc + 7)  # +7 for additional features

            # Core MFCC features
            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=self.n_mfcc,
                                      hop_length=self.hop_length, n_fft=self.n_fft)
            mfcc_mean = np.mean(mfcc.T, axis=0)

            # Additional acoustic features for better emotion recognition
            # 1. Spectral centroid (brightness)
            spectral_centroid = np.mean(librosa.feature.spectral_centroid(y=y, sr=sr))

            # 2. Zero crossing rate (voice activity)
            zcr = np.mean(librosa.feature.zero_crossing_rate(y))

            # 3. RMS energy
            rms = np.mean(librosa.feature.rms(y=y))

            # 4. Spectral rolloff
            rolloff = np.mean(librosa.feature.spectral_rolloff(y=y, sr=sr))

            # 5. Tempo and rhythm
            tempo, _ = librosa.beat.beat_track(y=y, sr=sr)

            # 6. Pitch (fundamental frequency)
            pitches, magnitudes = librosa.piptrack(y=y, sr=sr)
            pitch = np.mean(pitches[pitches > 0]) if len(pitches[pitches > 0]) > 0 else 0

            # 7. Audio duration (normalized)
            duration = len(y) / sr

            # Combine all features
            features = np.concatenate([
                mfcc_mean,
                [spectral_centroid, zcr, rms, rolloff, tempo, pitch, duration]
            ])

            return features

        except Exception as e:
            print(f"Error processing {file_path}: {str(e)}")
            return np.zeros(self.n_mfcc + 7)

    def smart_imputation(self, features, df, missing_mask):
        """Advanced imputation using multiple strategies"""
        print("🧠 Applying smart imputation strategies...")

        # Strategy 1: KNN imputation based on dialogue context
        dialogue_groups = df.groupby('Dialogue_ID')
        imputed_features = features.copy()

        for dia_id, group in dialogue_groups:
            group_indices = group.index
            group_features = features[group_indices]
            group_missing = missing_mask[group_indices]

            if np.any(~group_missing) and np.any(group_missing):
                # Use KNN imputation within dialogue
                imputer = KNNImputer(n_neighbors=min(3, np.sum(~group_missing)))
                group_imputed = imputer.fit_transform(group_features)
                imputed_features[group_indices] = group_imputed

        # Strategy 2: Emotion-based imputation for remaining missing values
        if 'Emotion' in df.columns:
            emotion_groups = df.groupby('Emotion')
            for emotion, group in emotion_groups:
                group_indices = group.index
                emotion_features = imputed_features[group_indices]
                emotion_missing = np.all(emotion_features == 0, axis=1)

                if np.any(~emotion_missing) and np.any(emotion_missing):
                    # Use mean features for this emotion
                    emotion_mean = np.mean(emotion_features[~emotion_missing], axis=0)
                    imputed_features[group_indices[emotion_missing]] = emotion_mean

        # Strategy 3: Global imputation for any remaining zeros
        still_missing = np.all(imputed_features == 0, axis=1)
        if np.any(still_missing):
            global_mean = np.mean(imputed_features[~still_missing], axis=0)
            imputed_features[still_missing] = global_mean

        return imputed_features

    def process_with_quality_control(self, df, batch_size=100, use_advanced_features=True):
        """Process with quality control and advanced imputation"""
        print("🎵 Starting enhanced audio processing...")

        # Create file index
        self.create_file_index()

        # Pre-check file availability
        print("🔍 Pre-checking file availability...")
        file_paths = []
        missing_count = 0

        for _, row in df.iterrows():
            key = (row['Dialogue_ID'], row['Utterance_ID'])
            if key in self.file_index:
                file_paths.append(self.file_index[key][0])
            else:
                file_paths.append(None)
                missing_count += 1

        print(f"📊 File availability:")
        print(f"   Available: {len(df) - missing_count:,} ({(len(df) - missing_count)/len(df)*100:.1f}%)")
        print(f"   Missing: {missing_count:,} ({missing_count/len(df)*100:.1f}%)")

        # Extract features
        feature_dim = self.n_mfcc + (7 if use_advanced_features else 0)
        all_features = []
        missing_mask = []

        print(f"🚀 Processing {len(df):,} files...")

        for i in tqdm(range(0, len(file_paths), batch_size), desc="Processing batches"):
            batch_paths = file_paths[i:i+batch_size]
            batch_features = []
            batch_missing = []

            for file_path in batch_paths:
                if file_path is None:
                    batch_features.append(np.zeros(feature_dim))
                    batch_missing.append(True)
                else:
                    if use_advanced_features:
                        features = self.extract_advanced_features(file_path)
                    else:
                        features = self.extract_basic_mfcc(file_path)
                    batch_features.append(features)
                    batch_missing.append(np.all(features == 0))

            all_features.extend(batch_features)
            missing_mask.extend(batch_missing)

        features_array = np.array(all_features)
        missing_mask = np.array(missing_mask)

        # Apply smart imputation
        if np.any(missing_mask):
            features_array = self.smart_imputation(features_array, df, missing_mask)

        # Normalize features
        features_array = self.scaler.fit_transform(features_array)

        # Quality metrics
        successful = np.sum(~missing_mask)
        imputed = np.sum(missing_mask)

        print(f"\n✅ Processing Results:")
        print(f"   Total samples: {len(df):,}")
        print(f"   Successfully extracted: {successful:,}")
        print(f"   Imputed samples: {imputed:,}")
        print(f"   Final feature shape: {features_array.shape}")
        print(f"   Feature mean: {np.mean(features_array):.4f}")
        print(f"   Feature std: {np.std(features_array):.4f}")

        return features_array, {
            'total_samples': len(df),
            'successful_extractions': successful,
            'imputed_samples': imputed,
            'feature_shape': features_array.shape,
            'feature_dim': feature_dim,
            'use_advanced_features': use_advanced_features
        }

    def extract_basic_mfcc(self, file_path):
        """Basic MFCC extraction (original method)"""
        try:
            full_path = os.path.join(self.audio_dir, file_path)
            y, sr = librosa.load(full_path, sr=self.sr)

            if len(y) == 0:
                return np.zeros(self.n_mfcc)

            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=self.n_mfcc)
            return np.mean(mfcc.T, axis=0)

        except Exception:
            return np.zeros(self.n_mfcc)

# Usage example and comparison
def compare_methods(df, audio_dir):
    """Compare original vs enhanced processing"""
    extractor = AudioFeatureExtractor(audio_dir)

    print("🔄 Comparing processing methods...")

    # Method 1: Original (basic MFCC with zero-padding)
    print("\n1️⃣ Original Method (Basic MFCC + Zero-padding)")
    features_basic, metadata_basic = extractor.process_with_quality_control(
        df, use_advanced_features=False
    )

    # Method 2: Enhanced (Advanced features + Smart imputation)
    print("\n2️⃣ Enhanced Method (Advanced Features + Smart Imputation)")
    features_enhanced, metadata_enhanced = extractor.process_with_quality_control(
        df, use_advanced_features=True
    )

    return {
        'basic': (features_basic, metadata_basic),
        'enhanced': (features_enhanced, metadata_enhanced)
    }

# Advanced missing data analysis
def analyze_missing_patterns_advanced(df, audio_dir):
    """Enhanced missing data analysis"""
    print("🔍 Advanced missing data analysis...")

    extractor = AudioFeatureExtractor(audio_dir)
    file_index = extractor.create_file_index()

    # Analyze patterns
    missing_by_dialogue = defaultdict(list)
    missing_by_emotion = defaultdict(int)
    missing_by_speaker = defaultdict(int)

    for _, row in df.iterrows():
        key = (row['Dialogue_ID'], row['Utterance_ID'])
        if key not in file_index:
            missing_by_dialogue[row['Dialogue_ID']].append(row['Utterance_ID'])
            if 'Emotion' in row:
                missing_by_emotion[row['Emotion']] += 1
            if 'Speaker' in row:
                missing_by_speaker[row['Speaker']] += 1

    print(f"📊 Missing Data Patterns:")
    print(f"   Dialogues affected: {len(missing_by_dialogue)}")
    print(f"   Emotions affected: {len(missing_by_emotion)}")
    print(f"   Speakers affected: {len(missing_by_speaker)}")

    # Recommendations
    missing_rate = len([item for sublist in missing_by_dialogue.values()
                      for item in sublist]) / len(df)

    print(f"\n💡 Recommendations:")
    if missing_rate > 0.5:
        print("   - High missing rate detected (>50%)")
        print("   - Consider data augmentation techniques")
        print("   - Use advanced imputation methods")
        print("   - Validate model performance carefully")
    elif missing_rate > 0.2:
        print("   - Moderate missing rate (20-50%)")
        print("   - Smart imputation recommended")
        print("   - Consider ensemble methods")
    else:
        print("   - Low missing rate (<20%)")
        print("   - Simple imputation sufficient")

    return {
        'missing_by_dialogue': dict(missing_by_dialogue),
        'missing_by_emotion': dict(missing_by_emotion),
        'missing_by_speaker': dict(missing_by_speaker),
        'missing_rate': missing_rate
    }

# Main processing function
def process_meld_audio_enhanced(df, audio_dir, output_dir):
    """Main function to process MELD audio with enhancements"""
    os.makedirs(output_dir, exist_ok=True)

    # Analyze missing patterns
    analysis = analyze_missing_patterns_advanced(df, audio_dir)

    # Process with enhanced method
    extractor = AudioFeatureExtractor(audio_dir)
    features, metadata = extractor.process_with_quality_control(df)

    # Save results
    np.save(os.path.join(output_dir, 'audio_features_enhanced.npy'), features)

    # Save metadata
    combined_metadata = {**metadata, **analysis}
    with open(os.path.join(output_dir, 'processing_metadata.json'), 'w') as f:
        json.dump(combined_metadata, f, indent=2, default=str)

    # Save scaler for future use
    import joblib
    joblib.dump(extractor.scaler, os.path.join(output_dir, 'feature_scaler.pkl'))

    print(f"\n💾 Results saved to: {output_dir}")
    print("✅ Enhanced audio processing complete!")

    return features, combined_metadata

"""## Video Feature Extraction Pipeline

Install Required Libraries
"""

!pip install opencv-python-headless torchvision --quiet

"""Import Dependencies"""

import os
import cv2
import numpy as np
import torch
import torchvision.transforms as transforms
from torchvision.models import resnet50
from tqdm import tqdm

"""Load Pretrained ResNet50 (without classification layer)"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

resnet = resnet50(pretrained=True)
resnet = torch.nn.Sequential(*list(resnet.children())[:-1])  # Remove final classifier
resnet.to(device).eval()

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

"""Frame Sampling & Feature Extraction"""

def extract_frames(video_path, max_frames=10):
    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frames = []

    step = max(1, total_frames // max_frames)

    for i in range(0, total_frames, step):
        cap.set(cv2.CAP_PROP_POS_FRAMES, i)
        ret, frame = cap.read()
        if not ret:
            continue
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame)
        if len(frames) >= max_frames:
            break

    cap.release()
    return frames

def extract_video_features(video_path, max_frames=10):
    frames = extract_frames(video_path, max_frames)
    features = []

    for frame in frames:
        try:
            input_tensor = transform(frame).unsqueeze(0).to(device)
            with torch.no_grad():
                embedding = resnet(input_tensor).squeeze().cpu().numpy()
            features.append(embedding)
        except Exception:
            continue

    return np.mean(features, axis=0) if features else np.zeros(2048)

"""Process All Videos in a Dataset Split"""

def process_video_split(df, video_dir, output_path):
    all_features = []
    missing = 0

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Extracting video features"):
        file_name = f'dia{row["Dialogue_ID"]}_utt{row["Utterance_ID"]}.mp4'
        video_path = os.path.join(video_dir, file_name)

        if not os.path.exists(video_path):
            all_features.append(np.zeros(2048))
            missing += 1
            continue

        features = extract_video_features(video_path)
        all_features.append(features)

    all_features = np.array(all_features)
    np.save(output_path, all_features)

    print(f"\n✅ Saved {len(df)} video features to: {output_path}")
    print(f"🚫 Missing files: {missing}")
    print(f"📐 Feature shape: {all_features.shape}")

"""Run on Train Split"""

video_dir = '/content/drive/MyDrive/MELD.Raw/train/train_splits'
output_path = '/content/drive/MyDrive/MELD.Raw/train_video_features.npy'

import multiprocessing as mp
from functools import partial
import numpy as np

def process_single_video(args):
    """Process a single video - designed for multiprocessing"""
    row, video_dir = args
    file_name = f'dia{row["Dialogue_ID"]}_utt{row["Utterance_ID"]}.mp4'
    video_path = os.path.join(video_dir, file_name)

    if not os.path.exists(video_path):
        return np.zeros(2048)

    return extract_video_features(video_path)

def process_video_split_fast(df, video_dir, output_path, num_workers=4):
    """Multi-threaded video processing"""

    # Prepare arguments for multiprocessing
    args = [(row, video_dir) for _, row in df.iterrows()]

    # Process in parallel
    with mp.Pool(num_workers) as pool:
        all_features = list(tqdm(
            pool.imap(process_single_video, args),
            total=len(df),
            desc="Extracting video features (parallel)"
        ))

    all_features = np.array(all_features)
    np.save(output_path, all_features)

    print(f"✅ Saved {len(df)} video features to: {output_path}")
    print(f"📐 Feature shape: {all_features.shape}")

# Usage
num_cores = mp.cpu_count()
print(f"Using {num_cores} CPU cores")
process_video_split_fast(train_df, video_dir, output_path, num_workers=num_cores)

"""Run on dev Split"""

video_dir = '/content/drive/MyDrive/MELD.Raw/dev/dev_splits_complete'
output_path = '/content/drive/MyDrive/MELD.Raw/dev_video_features.npy'

process_video_split(dev_df, video_dir, output_path)

"""Run on Test Split"""

video_dir = '/content/drive/MyDrive/MELD.Raw/test/output_repeated_splits_test'
output_path = '/content/drive/MyDrive/MELD.Raw/test_video_features.npy'

process_video_split(test_df, video_dir, output_path)



"""### Multimodal Dataset Preparation and Model Training

Load and Combine the Features

Each modality’s features are already extracted and saved as .npy. Now we’ll concatenate them.

Train
"""

import numpy as np
import pandas as pd

# Load features
X_text = np.load('/content/drive/MyDrive/MELD.Raw/train_text_embeddings.npy')
X_audio = np.load('/content/drive/MyDrive/MELD.Raw/train_audio_features.npy')
X_video = np.load('/content/drive/MyDrive/MELD.Raw/train_video_features.npy')

# Combine all modalities
X_train = np.hstack([X_text, X_audio, X_video])
print(X_train.shape)  # Expected: (N, total_feature_dim)

# Load labels
train_df = pd.read_csv('/content/drive/MyDrive/MELD.Raw/train_sent_emo.csv')
y_train = train_df['Emotion']  # or 'Sentiment'

# Load features
X_text_dev = np.load('/content/drive/MyDrive/MELD.Raw/dev_text_embeddings.npy')
X_audio_dev = np.load('/content/drive/MyDrive/MELD.Raw/dev_audio_features.npy')
X_video_dev = np.load('/content/drive/MyDrive/MELD.Raw/dev_video_features.npy')

# Combine all modalities
X_train_dev = np.hstack([X_text_dev, X_audio_dev, X_video_dev])
print(X_train_dev.shape)  # Expected: (N, total_feature_dim)

# Load labels
dev_df = pd.read_csv('/content/drive/MyDrive/MELD.Raw/dev_sent_emo.csv')
y_train_dev = dev_df['Emotion']  # or 'Sentiment'

# Load features
X_text_test = np.load('/content/drive/MyDrive/MELD.Raw/test_text_embeddings.npy')
X_audio_test = np.load('/content/drive/MyDrive/MELD.Raw/test_audio_features.npy')
X_video_test = np.load('/content/drive/MyDrive/MELD.Raw/test_video_features.npy')

# Combine all modalities
X_train_test = np.hstack([X_text_test, X_audio_test, X_video_test])
print(X_train_test.shape)  # Expected: (N, total_feature_dim)

# Load labels
test_df = pd.read_csv('/content/drive/MyDrive/MELD.Raw/test_sent_emo.csv')
y_train_test = test_df['Emotion']  # or 'Sentiment'

"""Encode the Labels

Train
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)

"""dev"""

le = LabelEncoder()
y_dev_encoded = le.fit_transform(y_train_dev)

"""Test"""

le = LabelEncoder()
y_test_encoded = le.fit_transform(y_train_test)

"""Train a Simple Multimodal Model (MLP)"""

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

model = MLPClassifier(hidden_layer_sizes=(512, 256), max_iter=100, random_state=42)
model.fit(X_train, y_train_encoded)

"""Evaluate on Validation Set"""

# Evaluate
y_pred = model.predict(X_train_dev)
print(classification_report(y_dev_encoded, y_pred, target_names=le.classes_))

"""Test and Save Final Results"""

y_pred_test = model.predict(X_train_test)
print(classification_report(y_test_encoded, y_pred_test, target_names=le.classes_))

"""| Phase                       | Description                                           |
| --------------------------- | ----------------------------------------------------- |
|  1. Improve Model         | Deep MLP + regularization + class weighting           |
|  2. Add Confidence System | Flag predictions below softmax threshold              |
|  3. Add Ambivalence Logic | Detect predictions where top-2 class scores are close |
|  4. Evaluate Impact       | Analyze system behavior & performance improvements    |

Improve the Multimodal Model

Compute Class Weights

To help with class imbalance (e.g., disgust, fear):

Load Features & Labels
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load features
X_text = np.load("/content/drive/MyDrive/MELD.Raw/train_text_embeddings.npy")
X_audio = np.load("/content/drive/MyDrive/MELD.Raw/train_audio_features.npy")
X_video = np.load("/content/drive/MyDrive/MELD.Raw/train_video_features.npy")

X_train = np.hstack((X_text, X_audio, X_video))

# Load labels
train_df = pd.read_csv("/content/drive/MyDrive/MELD.Raw/train_sent_emo.csv")
y_train = train_df["Emotion"]

# Encode labels
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)

print("X shape:", X_train.shape)
print("y shape:", y_train_encoded.shape)

# Load dev and test data
X_dev = np.hstack([
    np.load('/content/drive/MyDrive/MELD.Raw/dev_text_embeddings.npy'),
    np.load('/content/drive/MyDrive/MELD.Raw/dev_audio_features.npy'),
    np.load('/content/drive/MyDrive/MELD.Raw/dev_video_features.npy')
])
y_dev = pd.read_csv('/content/drive/MyDrive/MELD.Raw/dev_sent_emo.csv')['Emotion']
y_dev_encoded = le.transform(y_dev)

X_test = np.hstack([
    np.load('/content/drive/MyDrive/MELD.Raw/test_text_embeddings.npy'),
    np.load('/content/drive/MyDrive/MELD.Raw/test_audio_features.npy'),
    np.load('/content/drive/MyDrive/MELD.Raw/test_video_features.npy')
])
y_test = pd.read_csv('/content/drive/MyDrive/MELD.Raw/test_sent_emo.csv')['Emotion']
y_test_encoded = le.transform(y_test)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

X_dev_scaled = scaler.transform(X_dev)
X_test_scaled = scaler.transform(X_test)

"""Convert to PyTorch Dataset"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class MELDDataset(torch.utils.data.Dataset):
    def __init__(self, features, labels):
        self.X = torch.tensor(features, dtype=torch.float32)
        self.y = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return len(self.y)


    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_dataset = MELDDataset(X_train_scaled, y_train_encoded)
dev_dataset = MELDDataset(X_dev_scaled, y_dev_encoded)
test_dataset = MELDDataset(X_test_scaled, y_test_encoded)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
dev_loader = torch.utils.data.DataLoader(dev_dataset, batch_size=64)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=64)

"""Define the Multimodal MLP"""

import torch.nn as nn
import torch.nn.functional as F

class MultimodalMLP(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(MultimodalMLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, 1024)
        self.bn1 = nn.BatchNorm1d(1024)

        self.fc2 = nn.Linear(1024, 512)
        self.bn2 = nn.BatchNorm1d(512)

        self.fc3 = nn.Linear(512, 256)
        self.bn3 = nn.BatchNorm1d(256)

        self.fc4 = nn.Linear(256, 128)
        self.dropout = nn.Dropout(0.4)
        self.out = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.bn1(F.relu(self.fc1(x)))
        x = self.bn2(F.relu(self.fc2(x)))
        x = self.bn3(F.relu(self.fc3(x)))
        x = self.dropout(F.relu(self.fc4(x)))
        return self.out(x)



"""Set Up Training with Class Weights & LR Scheduler"""

# Class weights
from sklearn.utils.class_weight import compute_class_weight
import numpy as np


# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Class weights
from sklearn.utils.class_weight import compute_class_weight
class_weights = compute_class_weight('balanced', classes=np.unique(y_train_encoded), y=y_train_encoded)
weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)

# Model setup
model = MultimodalMLP(input_dim=X_train.shape[1], num_classes=len(le.classes_)).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.5)
loss_fn = nn.CrossEntropyLoss(weight=weights_tensor)

"""Train Model with Validation Accuracy Tracking"""

def train_model(model, train_loader, dev_loader, optimizer, scheduler, loss_fn, epochs=15):
    best_acc = 0.0

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            outputs = model(X_batch)
            loss = loss_fn(outputs, y_batch)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        scheduler.step()

        # Validation
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for X_val, y_val in dev_loader:
                X_val, y_val = X_val.to(device), y_val.to(device)
                preds = torch.argmax(model(X_val), dim=1)
                correct += (preds == y_val).sum().item()
                total += y_val.size(0)

        val_acc = correct / total
        print(f"Epoch {epoch+1} | Train Loss: {total_loss:.4f} | Dev Acc: {val_acc:.4f}")

        # Save best model
        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), "best_multimodal_model.pt")

train_model(model, train_loader, dev_loader, optimizer, scheduler, loss_fn, epochs=15)

"""Evaluation Function"""

from sklearn.metrics import classification_report
import numpy as np

def evaluate_model(model, X, y_true, threshold=0.6, ambivalence_delta=0.1):
    model.eval()
    with torch.no_grad():
        inputs = torch.tensor(X, dtype=torch.float32).to(device)
        logits = model(inputs)
        probs = torch.softmax(logits, dim=1).cpu().numpy()
        preds = np.argmax(probs, axis=1)

        # Confidence thresholding
        confidences = probs.max(axis=1)
        low_conf_mask = confidences < threshold

        # Ambivalence detection
        sorted_probs = np.sort(probs, axis=1)
        ambiv_diff = sorted_probs[:, -1] - sorted_probs[:, -2]
        ambiv_mask = ambiv_diff < ambivalence_delta

        print("🎯 Overall Performance:")
        print(classification_report(y_true, preds, target_names=le.classes_))

        print(f"\n⚠️ Low-Confidence Predictions: {np.sum(low_conf_mask)} / {len(y_true)}")
        print(classification_report(np.array(y_true)[low_conf_mask], preds[low_conf_mask], target_names=le.classes_))

        print(f"\n🌀 Ambivalent Predictions: {np.sum(ambiv_mask)} / {len(y_true)}")
        print(classification_report(np.array(y_true)[ambiv_mask], preds[ambiv_mask], target_names=le.classes_))

        return probs, preds, confidences, low_conf_mask, ambiv_mask

"""Load Best Model & Evaluate"""

# Load best model
best_model = MultimodalMLP(input_dim=X_train.shape[1], num_classes=len(le.classes_)).to(device)
best_model.load_state_dict(torch.load("best_multimodal_model.pt"))
best_model.eval()

# Evaluate on dev
print("\n📊 Evaluation on Dev Set")
evaluate_model(best_model, X_dev_scaled, y_dev_encoded)

# Evaluate on test
print("\n📊 Evaluation on Test Set")
evaluate_model(best_model, X_test_scaled, y_test_encoded)

"""Visualize Confidence Distribution"""

import matplotlib.pyplot as plt

def plot_confidence_histogram(confidences, title='Confidence Distribution'):
    plt.figure(figsize=(8, 4))
    plt.hist(confidences, bins=20, color='skyblue', edgecolor='black')
    plt.axvline(0.6, color='red', linestyle='--', label='Threshold (0.6)')
    plt.title(title)
    plt.xlabel('Confidence')
    plt.ylabel('Frequency')
    plt.legend()
    plt.grid(True)
    plt.show()

probs_test, preds_test, confidences_test, _, _ = evaluate_model(best_model, X_test_scaled, y_test_encoded)
plot_confidence_histogram(confidences_test, title='Test Set Confidence Distribution')

"""✅ Key Observations:
1. Model is Mostly Confident
Most predictions fall between 0.7 and 1.0, especially near 0.95–1.0.

This suggests the model often feels strongly about its top prediction — a good sign of certainty in its decisions.

2. Smooth Distribution with Right Skew
There's a right skew, meaning the model tends to be more confident than uncertain.

This implies the training process was successful: the model has learned clear signal patterns across modalities.

3. ~1,000 Predictions Below Threshold
The area left of the 0.6 threshold line represents “flagged” predictions (≈1,010 samples from previous output).

These predictions are where the model struggles or is unsure — which is where your confidence filtering system becomes valuable.

4. Wide Confidence Range
The model has learned to express a range of certainties, rather than always defaulting to 0.99 — this shows good probability calibration.

# Demo Setup
"""

from IPython.display import display, Video
import pandas as pd
import os
import torch
import numpy as np
from collections import defaultdict
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
import json
import warnings
warnings.filterwarnings('ignore')

# Ensure best_model, X_test_scaled, test_df, le, and device are defined before calling show_demo
# (These are expected based on the context provided)

def show_demo(index, df, X_scaled, video_dir, model):
    row = df.iloc[index]
    true_emotion = row['Emotion']
    dialogue_id = row['Dialogue_ID']
    utterance_id = row['Utterance_ID']
    text = row['Utterance']


    source_video_dir = '/content/drive/MyDrive/MELD.Raw/test/output_repeated_splits_test'
    video_filename = f"dia{dialogue_id}_utt{utterance_id}.mp4"
    video_path = os.path.join(source_video_dir, video_filename)

    # Display video
    print(f"🎞 Showing video: {video_filename}")
    # Added embed=True to correctly display the video from a local file path
    display(Video(video_path, width=320, embed=True))

    # Model inference
    # Ensure 'device' variable is defined (it's in Global Variables)
    x = torch.tensor(X_scaled[index], dtype=torch.float32).unsqueeze(0).to(device)
    best_model.eval() # Set model to evaluation mode
    with torch.no_grad(): # Disable gradient calculation
        logits = model(x)
    probs = torch.softmax(logits, dim=1).squeeze().cpu().numpy()

    # Ensure 'le' (LabelEncoder) variable is defined (it's in Global Variables)
    top1 = np.argmax(probs)
    # Ensure there are at least 2 classes to get top2
    if len(le.classes_) > 1:
        top2 = np.argsort(probs)[-2]
        ambiv_margin = probs[top1] - probs[top2]
    else:
        top2 = -1 # No second best if only one class
        ambiv_margin = 0.0 # No ambivalence if only one class

    confidence = probs[top1]

    pred_emotion = le.classes_[top1]

    # Flag logic
    low_conf_flag = confidence < 0.6
    # Check ambivalence only if there's more than one class
    ambiv_flag = False
    if len(le.classes_) > 1:
        ambiv_flag = ambiv_margin < 0.1


    # Display info
    print(f"\n🗣 Utterance: {text}")
    print(f"🎯 Predicted Emotion: {pred_emotion}")
    print(f"🔒 Confidence: {confidence:.3f}")
    # Only print ambivalence if applicable
    if len(le.classes_) > 1:
        print(f"🌀 Ambivalence Margin: {ambiv_margin:.3f}")
    print(f"✅ True Emotion: {true_emotion}")

    # Flags
    if low_conf_flag:
        print("⚠️ Low confidence prediction")
    if ambiv_flag:
        print("🌀 Ambivalent (Top-2 emotions too close)")

    # Show probability table
    prob_df = pd.DataFrame({
        'Emotion': le.classes_,
        'Probability': [f"{p:.2%}" for p in probs]
    }).sort_values(by='Probability', ascending=False)

    display(prob_df.reset_index(drop=True))

    # Human-readable emoji summary
    emoji_map = {
        'anger': '😠', 'disgust': '🤢', 'fear': '😨',
        'joy': '😄', 'neutral': '😐', 'sadness': '😢', 'surprise': '😲'
    }

    print("\n📋 Summary:")
    print(f"🎯 Prediction: {emoji_map.get(pred_emotion, '')} {pred_emotion} ({confidence:.1%} confidence)")
    print(f"✅ Ground Truth: {emoji_map.get(true_emotion, '')} {true_emotion}")
    if low_conf_flag:
        print("⚠️ Flagged: Low confidence")
    if ambiv_flag:
        print("🌀 Flagged: Ambivalent (emotion overlap)")

# Example usage
# Make sure best_model, X_test_scaled, and test_df are loaded/available
# The global variables indicate device, le, and model exist.
# Assuming X_test_scaled and test_df were loaded/created in previous steps.
show_demo(index=42,
          df=test_df,
          X_scaled=X_test_scaled,
          video_dir="/content/drive/MyDrive/MELD.Raw/test", # This is not the direct video file directory
          model=best_model) # Using the 'model' variable from global scope, assuming it's the best_model



# Save model to file
torch.save(best_model.state_dict(), "best_multimodal_model.pt")

content = '''
import numpy as np
import librosa
from transformers import BertTokenizer, BertModel
import torch
import cv2
import os
from torchvision import models, transforms
from moviepy.editor import VideoFileClip
import tempfile

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load models
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model = BertModel.from_pretrained("bert-base-uncased").to(device)
resnet = models.resnet50(pretrained=True).to(device)
resnet.eval()

video_transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

def extract_text_features(text):
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128).to(device)
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()

def extract_audio_features(video_path, n_mfcc=13):
    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as tmp_audio:
        audio_path = tmp_audio.name
    try:
        video = VideoFileClip(video_path)
        video.audio.write_audiofile(audio_path, codec='pcm_s16le', verbose=False, logger=None)
        y, sr = librosa.load(audio_path, sr=22050)
        if len(y) == 0:
            return np.zeros(n_mfcc)
        mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
        return np.mean(mfcc.T, axis=0)
    except Exception as e:
        return np.zeros(n_mfcc)

def extract_video_features(video_path, max_frames=10):
    cap = cv2.VideoCapture(video_path)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    indices = np.linspace(0, frame_count - 1, num=max_frames, dtype=np.int32)
    frames = []
    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ret, frame = cap.read()
        if ret:
            img = video_transform(frame).unsqueeze(0).to(device)
            with torch.no_grad():
                features = resnet(img)
            frames.append(features.squeeze().cpu().numpy())
    cap.release()
    return np.mean(frames, axis=0) if frames else np.zeros(2048)

def extract_combined_features(video_path, text):
    text_feat = extract_text_features(text)
    audio_feat = extract_audio_features(video_path)
    video_feat = extract_video_features(video_path)
    return np.concatenate([text_feat, audio_feat, video_feat])
'''

with open('feature_extraction.py', 'w') as file:
    file.write(content)

print("The Python script has been successfully saved to 'feature_extraction.py'")

code_content = '''
import streamlit as st
import torch
import numpy as np
import tempfile
from model import MultimodalMLP
from feature_extraction import extract_combined_features
from sklearn.preprocessing import LabelEncoder

# Load label encoder
le = LabelEncoder()
le.classes_ = np.array(['anger', 'disgust', 'fear', 'joy', 'neutral', 'sadness', 'surprise'])

# Load model
model = MultimodalMLP(input_dim=2829, num_classes=7)
model.load_state_dict(torch.load("best_multimodal_model.pt", map_location='cpu'))
model.eval()

# Emoji map
emoji_map = {
    'anger': '😠', 'disgust': '🤢', 'fear': '😨',
    'joy': '😄', 'neutral': '😐', 'sadness': '😢', 'surprise': '😲'
}

# UI
st.set_page_config(page_title="Multimodal Sentiment App", layout="centered")
st.title("🎬 Multimodal Sentiment Analyzer")
st.markdown("Upload a short video clip and enter the spoken text to detect emotion.")

uploaded_file = st.file_uploader("Upload .mp4 video", type=["mp4"])
text_input = st.text_input("Enter the spoken text (utterance)")

if uploaded_file is not None and text_input:
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as tmp:
        tmp.write(uploaded_file.read())
        video_path = tmp.name

    st.video(video_path)

    st.info("Processing video, audio, and text features...")
    features = extract_combined_features(video_path, text_input)
    x = torch.tensor(features, dtype=torch.float32).unsqueeze(0)

    with torch.no_grad():
        logits = model(x)
        probs = torch.softmax(logits, dim=1).squeeze().numpy()

    top1 = np.argmax(probs)
    top2 = np.argsort(probs)[-2]
    confidence = probs[top1]
    margin = probs[top1] - probs[top2]
    pred_emotion = le.classes_[top1]

    # Display results
    st.success(f"🎯 Predicted Emotion: {emoji_map[pred_emotion]} {pred_emotion}")
    st.write(f"🔒 Confidence: `{confidence:.2%}`")
    st.write(f"🌀 Ambivalence Margin: `{margin:.2f}`")

    if confidence < 0.6:
        st.warning("⚠️ Low-confidence prediction")
    if margin < 0.1:
        st.warning("🌀 Ambivalent (emotion overlap)")

    st.subheader("📊 Full Emotion Probabilities")
    st.dataframe(
        {label: f"{probs[i]:.2%}" for i, label in enumerate(le.classes_)},
        use_container_width=True
    )

'''

with open('app.py', 'w') as file:
    file.write(code_content)

print("The Python script has been successfully saved to 'app.py'")



code_model = '''
import torch.nn as nn
import torch.nn.functional as F

class MultimodalMLP(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(BetterMultimodalMLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, 1024)
        self.bn1 = nn.BatchNorm1d(1024)

        self.fc2 = nn.Linear(1024, 512)
        self.bn2 = nn.BatchNorm1d(512)

        self.fc3 = nn.Linear(512, 256)
        self.bn3 = nn.BatchNorm1d(256)

        self.fc4 = nn.Linear(256, 128)
        self.dropout = nn.Dropout(0.4)
        self.out = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.bn1(F.relu(self.fc1(x)))
        x = self.bn2(F.relu(self.fc2(x)))
        x = self.bn3(F.relu(self.fc3(x)))
        x = self.dropout(F.relu(self.fc4(x)))
        return self.out(x)
'''

with open('model.py', 'w') as file:
    file.write(code_model)

print("The Python script has been successfully saved to 'model.py'")

